apiVersion: v1
kind: Service
metadata:
  name: spring-boot-k8s-demo-service
  namespace: default
spec:
  type: LoadBalancer
  selector:
    app: spring-boot-k8s-demo
    version: v1
    color: blue
  ports:
  - protocol: TCP 
    port: 80
    targetPort: spring-port
